### ISSUE TITLE
Global Variables Not Displaying in Menus

### ISSUE THREAD

**Issue by ParadiddlePride** [BetonQuest/RPGMenu#12]
## Bug report

**Spigot version:** `<!-- put your servers spigot version here -->` git-Spigot-3cb9dcb-77ca7ca (MC: 1.13.2)

**RPGMenu version:** `<!-- put your RPGMenu version here -->` v3.1-preview.1 (Bundaburg Preview)

**BetonQuest version:** `<!-- put your BetonQuest version here -->` 2.0-preview.21

### Description:

Global variables are not displaying properly inside menus. They work correctly in events, but only display as text when you hover over a button. It displays as such: http://prntscr.com/mvx2cf
However, if you click the button it will fire the event, which uses the same variables: http://prntscr.com/mvx315
Here is the button from the menu:
```
  recipe_Coffee:
    item: menu_recipePotion
    conditions: recipeCoffeeLvl,invCheckCoffee
    text:
      - '&6Coffee'
      - '&d&lReq. Lvl&7: &f&l$lvlReqCoffee$'
      - '&fIncome &7- &a$incomeGainCoffee$'
      - '&fEXP &7- &a$expGainCoffee$'
      - '&f# in Inventory &7- &a%item.brewCoffee.amount%'
      - '&bClick to Serve this brew!'
    click: brewCheckCoffee
    close: false

```
And here's the events being fired upon click:
```
brewCheckCoffee: if brewCheckCoffee brewServeCoffee else brewFAILMessage
brewServeCoffee: run ^money $incomeGainCoffee$ ^nujobs_addexp Bartender $expGainCoffee$ ^take brewCoffee:1 ^folder brewServeMsgCoffee
```

Finally, here is the variables from main.yml
```
  lvlReqCoffee: 3
  incomeGainCoffee: 5.5
  expGainCoffee: 0.5
```

### How to reproduce:

1) Create a menu
2) Make a global variable within main.yml
3) Use the variable on a button in your menu
### Checklist:

- [X] I included all versions (use `/version` command)
- [X] I made sure there aren't duplicates of this report [(use Search)](https://github.com/joblo2213/RPGMenu/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3ABug+)
- [X] I made sure I am using an up-to-date version of RPGMenu
- [X] I made sure the bug/error is not caused by any other plugin
